datasets:
    "scannet0024":
        scene_path: /HD/scannet/scene0024_00/npbg_scene.yaml
        target_path: /HD/scannet/scene0024_00/color
        target_name_func: "lambda i: f'{i}.jpg'"
        # mask_path: masks_undistorted
        # mask_name_func: "lambda i: f'{i}.png'"
