datasets:
    "church_anime":
        scene_path: /home/dari/Projects/pointrendering2/Code/scenes/church/npbg_scene.yaml
        target_path: /home/dari/Projects/pointrendering2/Code/scenes/church/color
        target_name_func: "lambda i: f'{i}.jpg'"
        # mask_path: masks_undistorted
        # mask_name_func: "lambda i: f'{i}.png'"
    "church_chiptune":
        scene_path: /home/dari/Projects/pointrendering2/Code/scenes/church/npbg_scene.yaml
        target_path: /home/dari/Projects/pointrendering2/Code/scenes/church/color
        target_name_func: "lambda i: f'{i}.jpg'"
        # mask_path: masks_undistorted
        # mask_name_func: "lambda i: f'{i}.png'"
